#!/usr/bin/env node

const fs = require('fs')
const request = require('request')
const dateformat = require('dateformat')
const cheerio = require('cheerio')
const Company = require('./Model/Company')

const KMUST = {
  url: 'http://kmlg.bibibi.net/module/careers', // 基本页面
  range: [1506787200000, Date.now()], // 时间范围
  getCount: 'http://kmlg.bibibi.net/module/getcareers?is_total=1&start=0&count=0&keyword=&type=inner&day=!#!date!#!',
  getList: 'http://kmlg.bibibi.net/module/getcareers?start_page=1&keyword=&type=inner&day=!#!date!#!&count=15&start=1',
  getDetail: 'http://kmlg.bibibi.net/detail/career?id=!#!career_talk_id!#!'
}
const YNU = 'http://jobs.ynu.edu.cn/'
let list = []

function loader(url){
  return new Promise((resolve, reject) => {
    request.get(url, (err, response, body) => {
      if (err) {
        return reject(err)
      }
      resolve(body)
    })
  })
}

function handleSave(object = {}) {
  return new Promise((resolve, reject) => {
    Company.findOne({ career_talk_id: object.career_talk_id }, (err, doc) => {
      if (!err && doc) {
        doc.remove()
        console.log('删除并更新')
        Company.create(object, (err, doc) => {
          if (err) {
            console.error(err)
            return reject(err)
          }
          resolve(doc)
        })
      } else {
        Company.create(object, (err, doc) => {
          if (err) {
            console.error(err)
            return reject(err)
          }
          resolve(doc)
        })
      }
    })
  })
}

function loadData(date, url) {
  if (!date) {
    throw new Error('爬取日期不能为空')
  }
  url = url || KMUST.getCount.replace('!#!date!#!', date)
  loader(url).then((body) => {
    if (body < 0) {
      return 0
    }
    // 加载当天的列表
    url = KMUST.getList.replace('!#!date!#!', date)
    loader(url).then((body) => {
      const data = JSON.parse(body)
      data.data.forEach((item) => {
        url = KMUST.getDetail.replace('!#!career_talk_id!#!', item.career_talk_id)
        item.url = url
        list.push(item)
        handleSave(item).then((doc) => {
          console.log(doc.company_name, '存储成功')
        })
      })
    })
  }).catch((e) => {
    console.error('发生错误: ', e)
  })

}

// 开始时间
const start = 1519862400000
const day = 86400 * 1000
const today = Date.now()
let i = 0
function handleLoop() {
  const time = day * i + start
  const date = dateformat(time, 'yyyy-mm-dd')
  if (time > today) {
    console.log('结束爬取')
    require('./ynu')
    return
  }
  // 开始加载
  loadData(date)
  console.log('爬取: ', date)
  i++
  setTimeout(handleLoop, 100)
}

handleLoop()

